name: "CI"
on:
  pull_request:
  push:
  create:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: enable kvm to build docker image
      run: sudo sed -E '/system-features/s/$/ kvm/' -i /etc/nix/nix.conf
    - run: nix build
    - run: nix build '.#packages.x86_64-linux.withings-weights-image'
    - run: nix flake check
  publish:
    needs: tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: docker/setup-buildx-action@v2
    - name: Extract tag name
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF##*/})"
      id: extract_tag
    - run: nix build '.#packages.x86_64-linux.withings-weights-image'
    - run: docker load -i result
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker tag blackheaven/withings-weights:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
    - run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
